### ISSUE TITLE
Link to index.js

### ISSUE THREAD

**Issue by harryhaigh** [stldo/gatsby-plugin-create-page-html#1] opened 2021-03-05 06:01 UTC
I got this plugin to work when Linking to other pages.  But i always get an 404 error when linking back to "/" (Home).
I had to add the .html to the end of the 'to' attribute as the trailing slashes plugin didn't work.

<nav>
      <ul>
        <li>
          <Link to="/">
            Home <Lines />
          </Link>
        </li>
        {loggedIn.verified && (
          <li>
            <Link className="staffDetails" to="/modules/staff.html">
              <span className="staffText">Staff details</span> <Lines />
            </Link>
          </li>
        )}
        <li>
</ul>
</nav>

**Comment by stldo** [comment] 2021-03-07 16:07
Hi! It looks that your post is missing part of the content. Could you please share more information about the issue? Which other pages? Are you adding `.html` extensions to all links, including `/`? The issue is on development or production environment? The only thing this plugin does is generating `.html` copies of each path, so I need more information to see why it's causing any errors.

**Comment by stldo** [comment] 2021-04-26 22:39
I'm closing this issue. If you still need help, please let me know.

**Closed by stldo** 2021-04-26 22:39 UTC
